import Head from "next/head";
import { Inter } from "next/font/google";
import RecentlyPlayed from "@/components/RecentlyPlayed";


const inter = Inter({ subsets: ["latin"] });

const Home = () => {
  return (
    <>
      <Head>
        <title>Thythimical App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="font-roboto">
        <div>miao</div>
        <RecentlyPlayed />

        <button>button</button>
        
      </div>
    </>
  );
};
export default Home;
