import Head from "next/head";
import { Inter } from "next/font/google";
import { useEffect, useContext } from "react";
import { PlayerContext } from "@/contexts/playerContext";
import { IMusicDetail } from "@/interfaces/music";

interface Props {
  musicData: {
    code: number;
    data: IMusicDetail[];
  };
}

const inter = Inter({ subsets: ["latin"] });

const Home = ({ musicData }: Props) => {
  const { setPlayerList } = useContext(PlayerContext);
  useEffect(() => {
    setPlayerList(musicData.data);
  }, [musicData.data]);

  const handleButton = () => {
    setPlayerList(musicData.data.reverse());
    console.log("setPlayerList complete from index component");
  };

  return (
    <>
      <Head>
        <title>Thythimical App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="font-roboto">
        <div>Home page</div>
      </div>
    </>
  );
};
export default Home;

export const getServerSideProps = async () => {
  const musicData = await fetch(
    `${process.env.NEXT_MUSIC_SERVER_ADDRESS}/song/url/v1?id=108242,25727803,399354373,108914,26305541&level=lossless`
  ).then((res) => res.json());
  return {
    props: { musicData },
  };
};
